#!/usr/bin/env python3

""" netbox2aquilon - script to extract data out of netbox and use it to create aquilon entities."""

import argparse
import configparser
import logging
import os.path
import subprocess
import sys

import requests
import pynetbox as nb


CONFIG = configparser.ConfigParser()
CONFIG['netbox'] = {
    'url': 'https://netbox.example.org/',
    'cert_path': '',
    'token': 'TOKEN',
}
CONFIG['aquilon'] = {
    'archetype': 'ral-tier1',
    'osname': 'rocky',
    'osversion': '8x-x86_64',
    'cli_path': '/opt/aquilon/bin/aq.py',
    'domain': 'staging',
}
CONFIG.read([
    '/var/quattor/etc/' + os.path.basename(__file__) + '.cfg',
    os.path.expanduser('~/.netbox2aquilon.cfg'),
])


# connect to NetBox and set up session
NETBOX_SESSION = requests.Session()

if CONFIG['netbox']['cert_path']:
    if CONFIG['netbox']['cert_path'].lower() == 'false':
        NETBOX_SESSION.verify = False
    else:
        NETBOX_SESSION.verify = CONFIG['netbox']['cert_path']

NETBOX = nb.api(CONFIG['netbox']['url'], token=CONFIG['netbox']['token'])
NETBOX.http_session = NETBOX_SESSION


def _get_device_by_magdb_id(magdb_id):
    # get device from NetBox based on their MagDB system ID
    device = NETBOX.dcim.devices.get(cf_magdb_system_id=magdb_id)

    if device is None:
        logging.error("Device not found in NetBox")
        sys.exit(1)

    logging.debug("Got device %s for MagDB ID %s", device, magdb_id)
    return device


def _get_device_by_name(name):
    device = NETBOX.dcim.devices.get(name=name)

    if device is None:
        logging.error("Device not found in NetBox")
        sys.exit(1)

    logging.debug("Got device %s for name %s", device, name)
    return device


def _get_device_by_hostname(hostname):
    ip_address = NETBOX.ipam.ip_addresses.get(dns_name=hostname)
    if ip_address is None:
        logging.error("Hostname not found in NetBox")
        sys.exit(1)

    logging.debug("Got IP %s for hostname %s", ip_address, hostname)
    device = ip_address.assigned_object.device

    if device is None:
        logging.error("Device not found in NetBox")
        sys.exit(1)

    logging.debug("Got device %s for hostname %s", device, hostname)
    return device


def _get_device(opts):
    if opts.magdb_id:
        device = _get_device_by_magdb_id(opts.magdb_id)
    elif opts.netboxname:
        device = _get_device_by_name(opts.netboxname)
    elif opts.hostname:
        device = _get_device_by_hostname(opts.hostname)
    else:
        logging.error("No device specification provided")
        sys.exit(2)

    # check if device has a primary ip
    if device.primary_ip is None:
        logging.error("No primary IP defined for host")
        sys.exit(1)

    # check if device has a tenant
    if device.tenant is None:
        logging.error("No tenant defined for host")
        sys.exit(1)

    return device


def _get_rack_from_device(device):
    # check if host is in rack - query netbox for rack
    rack = NETBOX.dcim.racks.get(device.rack.id)

    if rack is None:
        logging.error("host not in rack?")
        sys.exit(1)

    # check facility_id is present
    if rack.facility_id is None:
        logging.error("no facility ID found for rack")
        sys.exit(1)

    return rack


def _get_interfaces_from_device(device):
    # next step is to add interfaces to the machine in Aquilon
    # We need to use 'filter' to retrieve the interface id for all interfaces
    # This will assume that the device name IS UNIQUE
    filter_interfaces = NETBOX.dcim.interfaces.filter(device=device.name)

    if len(filter_interfaces) == 0:
        logging.error("No interfaces found")
        sys.exit(1)

    interfaces = []
    unusedintf = 0
    for interface in filter_interfaces:
        if interface.mac_address:
            interfaces.append(interface)
        else:
            unusedintf += 1

    if unusedintf:
        logging.warning("%s interfaces without mac address were not included", unusedintf)

    return interfaces


def _get_current_sandbox():
    sandbox = None
    git_rev_parse = subprocess.run(
        ['git', 'rev-parse', '--show-toplevel'],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if git_rev_parse.returncode == 0:
        sandbox = b'/'.join([
            os.path.basename(os.path.dirname(git_rev_parse.stdout)),
            os.path.basename(git_rev_parse.stdout.strip()),
        ]).decode('utf-8')
    return sandbox


def _call_aq(opts, cmds):
    for cmd in cmds:
        if opts.dryrun:
            print('aq ' + cmd)
        else:
            retval = subprocess.call([CONFIG['aquilon']['cli_path']]+cmd.split(' '))
            if retval != 0:
                logging.error('Commmand %s %s exited with error code %d', CONFIG['aquilon']['cli_path'], cmd, retval)
                sys.exit(1)


def netbox_copy(opts):
    """
    Queries NetBox for a device based on it's MagDB system ID

    Takes 1 parameter:
    opts - a dict of options configured from commandline parameters
    """
    cmds = []

    # Should MagDB style naming be preserved for this host?
    preserve_magdb_naming = False

    device = _get_device(opts)

    # Preserve MagDB style machine naming for migrated hosts
    machine_name = 'netbox-%d' % device.id
    if device.custom_fields['magdb_system_id']:
        preserve_magdb_naming = True
        machine_name = 'system%d' % device.custom_fields['magdb_system_id']

    # check if host is in rack - query netbox for rack
    rack = _get_rack_from_device(device)

    # Default naming convention for new racks
    rack_name = '%s-%s' % (device.site.facility.lower(), rack.facility_id)

    # Preserve magdb2aquilon style names for migrated racks
    if preserve_magdb_naming:
        rack_name = '%srack%s' % (device.site.facility.lower(), rack.facility_id)

    cmds.append("add_machine --machine %s --model %s --rack %s" % (
        machine_name,
        device.device_type.slug,
        rack_name,
    ))

    interfaces = _get_interfaces_from_device(device)
    for interface in interfaces:
        cmds.append('add_interface --machine %s --mac %s --interface %s' % (
            machine_name,
            interface.mac_address,
            interface.name,
        ))


    if opts.sandbox:
        aqdesttype = 'sandbox'
        aqdestval = opts.sandbox
    elif opts.domain:
        aqdesttype = 'domain'
        aqdestval = opts.domain

    # Finally add the host to the machine
    cmds.append('add_host --hostname %s --machine %s --archetype %s --ip %s --personality %s-%s --%s %s --osname %s --osversion %s' % (
        device.primary_ip.dns_name,
        machine_name,
        opts.archetype,
        device.primary_ip.address.split('/')[0],
        device.device_role.slug,
        device.tenant.slug,
        aqdesttype,
        aqdestval,
        opts.osname,
        opts.osvers,
    ))

    _call_aq(opts, cmds)


if __name__ == "__main__":
    logging.basicConfig(format='%(levelname)s: %(message)s')

    PARSER = argparse.ArgumentParser()

    AQDEST = PARSER.add_mutually_exclusive_group()
    AQDEST.add_argument(
        "--sandbox", "-s",
        help="Name of the sandbox in user/sandbox format to add the copied host to",
    )
    AQDEST.add_argument(
        "--domain", "-d",
        help="Name of the domain to add the copied host to",
    )

    HOSTID = PARSER.add_mutually_exclusive_group(required=True)
    HOSTID.add_argument(
        "--hostname",
        help="Fully qualified domain name of host to copy from Netbox.",
    )
    HOSTID.add_argument(
        "--netboxname", "-n",
        help="Name of device to copy from Netbox.",
    )
    HOSTID.add_argument(
        "--magdb_id", "-m",
        help="MagDB system ID of host to copy from Netbox.",
    )

    PARSER.add_argument(
        "--archetype", "-a", default=CONFIG['aquilon']['archetype'],
        help="Destination aquilon archetype for the host to be copied. Default: " + CONFIG['aquilon']['archetype'],
    )
    PARSER.add_argument(
        "--osname", default=CONFIG['aquilon']['osname'],
        help="Name of the Operating system on the host. Default: " + CONFIG['aquilon']['osname'],
    )
    PARSER.add_argument(
        "--osvers", default=CONFIG['aquilon']['osversion'],
        help="Version of the Operating system on the host. Default: " + CONFIG['aquilon']['osversion'],
    )
    PARSER.add_argument(
        "--dryrun", action='store_true',
        help="Do not do anything to aquilon, instead print what would be done (currently true if not specified)",
    )
    PARSER.add_argument(
        "--debug", action='store_true',
        help="Set logging level to debug.",
    )
    OPTS, ARGS = PARSER.parse_known_args()

    if OPTS.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    # If domain or sandbox have not been provided, then see if the command is being run from sandbox,
    # if not, then use the domain configured as default.
    if not OPTS.domain and not OPTS.sandbox:
        OPTS.sandbox = _get_current_sandbox()
        if not OPTS.sandbox:
            OPTS.domain = CONFIG['aquilon']['domain']

    netbox_copy(OPTS)
